# Generated by Django 4.2.1 on 2023-06-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoinfo',
            name='body',
        ),
    ]
